ls:
  .dir: kebab-case | regex:^\..+$
  .ts: kebab-case
  .tsx: kebab-case
  .mjs: kebab-case
  .json: kebab-case
  .yml: kebab-case
  .yaml: kebab-case
  .svg: kebab-case
  .d.ts: kebab-case
  .config.ts: kebab-case
  .config.mjs: kebab-case
  .md: kebab-case | SCREAMING_SNAKE_CASE

  src:
    .dir: kebab-case
    .ts: kebab-case
    .tsx: kebab-case
    .css: kebab-case
    .spec.ts: kebab-case
    .spec.tsx: kebab-case

ignore:
  - node_modules
  - dist
  - .git
  - .claude
  - .github
  - src-tauri
  - public
  - .ls-lint.yml
  - .oxlintrc.json
  - .oxfmtrc.json
