export const fontNameTableIds = [
  "Copyright",
  "Font Family name",
  "Font Subfamily name",
  "Unique font identifier",
  "Full font name",
  "Version string",
  "PostScript name",
  "Trademark",
  "Manufacturer",
  "Designer",
  "Description",
  "URL Vendor",
  "URL Designer",
  "License Description",
  "License Info URL",
  "Reserved",
  "Typographic Family name",
  "Typographic Subfamily name",
  "Compatible Full (Macintosh only)",
  "Sample text",
  "PostScript CID findfont name",
  "WWS Family Name",
  "WWS Subfamily Name",
  "Light Background Palette",
  "Dark Background Palette",
  "Variations PostScript Name Prefix",
];
